### PR TITLE
IcoCrowdsale contract

### PR DESCRIPTION
**Pull request by harzo**
IcoCrowdsale contract is ready to review.

### CODE REVIEW

**Comment by jstefanski** [comment]
Please fix the PR title and resolve conflicts with `master` by rebasing.

**Comment by harzo** [comment]
@jstefanski this pull request is ready to review. Thanks in advance :+1:

**Comment by jstefanski** [comment]
I have a lot of failing test cases on this branch. Can you guys update me on the state of this PR?

**Comment by harzo** [comment]
@jstefanski Rebase master done. All tests are passing.

**Pull request merged**
